apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-controller
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: jahans.local.com
    http:
      paths:
      - path: /nginx
        backend:
          serviceName: nginx
          servicePort: 80
