kind: Namespace
apiVersion: v1
metadata:
  name: jahans-kube
---
kind: Service
apiVersion: v1
metadata:
  name: javaservice
spec:
  selector:
    app: javaservice
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: javaservice
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: javaservice
    spec:
      containers:
        - name: java
          image: "java:javaservice"
