kind: Service
apiVersion: v1
metadata:
  name: redis-service
spec:
  selector:
    app: redisPods
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 6379
