---
kind: Service
apiVersion: v1
metadata:
  name: cnode
spec:
  selector:
    app: cnode
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: cnode
spec:
  template:
    metadata:
      labels:
        app: cnode
    spec:
      containers:
        - name: cnode
          image: cnode:0.0.1

