kind: Namespace
apiVersion: v1
metadata:
  name: couchbase-kube
---
kind: Service
apiVersion: v1
metadata:
  name: couchbase3
spec:
  selector:
    app: couchbase3
  ports:
    - name: "cbport1"
      protocol: "TCP"
      port: 8091
      targetPort: 8091
    - name: "cbport2"
      protocol: "TCP"
      port: 8092
      targetPort: 8092
    - name: "cbport3"
      protocol: "TCP"
      port: 8093
      targetPort: 8093
    - name: "cbport4"
      protocol: "TCP"
      port: 8094
      targetPort: 8094
    - name: "cbport5"
      protocol: "TCP"
      port: 11210
      targetPort: 11210
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: couchbase3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: couchbase3
    spec:
      containers:
        - name: couchbase3
          image: "couchbase:latest"
