---
kind: Service
apiVersion: v1
metadata:
  name: gvedis
spec:
  selector:
    app: gvedis
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: gvedis
spec:
  template:
    metadata:
      labels:
        app: gvedis
    spec:
      containers:
        - name: gvedis
          image: gvedis:0.0.1
      initContainers:
      - name: init-myservice
        image: busybox
        command: ['sh', '-c', 'until nslookup redis; do echo waiting for redis; sleep 2; done;']

